sudo: false
language: python
env:
  matrix:
    - ENV=test
    - ENV=check
matrix:
  allow_failures:
    # Needs to be fixed!
    - env: ENV=test
install:
  - |
    if [ "$ENV" = "check" ]; then
      pip install vim-vint
    else
      pip install pytest
    fi
script:
  - vim --version
  - |
    if [ "$ENV" = "check" ]; then
      vint after autoload ftplugin plugin
    else
      pytest
    fi
