sudo: false
language: python
python: 3.6
env:
  matrix:
    - ENV=test_coverage
    - ENV=check
    - ENV=test_nvim
install:
  - |
    if [ "$ENV" = "test_coverage" ]; then
      python3.6 -m pip install pytest pytest-cov
    fi
  - |
    # https://github.com/neovim/bot-ci#generated-builds
    if [ "$ENV" = "test_nvim" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      pip --version
      pip install neovim
    else
      vim --version
    fi
script:
  - make --keep-going "$ENV"

after_script:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X fix -X search -X xcode -f coverage.xml
