sudo: false
language: python
python: 3.6
env:
  matrix:
    - ENV=test
    - ENV=check
    - ENV=test_coverage
matrix:
  include:
    - env: ENV=test_coverage
      python: 2.7
install:
  - |
    if [ "$ENV" = "test" ]; then
      python3.6 -m pip install pytest
    fi
  - |
    # https://github.com/neovim/bot-ci#generated-builds
    if [ "$ENV" = "test_coverage" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      pip --version
      pip install neovim pytest-cov
    else
      vim --version
    fi
script:
  - make --keep-going "$ENV"

after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy -X fix -X search -X xcode -f coverage.xml -F py${TRAVIS_PYTHON_VERSION//./}
