name: ci
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        run: |
          sudo pip install pytest
          vim --version

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: 'make test'

  code-quality:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        run: |
          vim --version
          make check
